name: Code Quality and API Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  code-tests:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: "${{ github.workspace }}/src"
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 pytest pytest-asyncio
        
    - name: Syntax check with flake8
      run: |
        flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics
        
    - name: Run syntax and import tests
      run: |
        python -m pytest tests/test_syntax.py -v
    
    - name: Run API tests
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        python -m pytest tests/test_api.py -v
