name: Validate Production Code

on:
  push:
    branches: [ '**' ]
    paths:
      - 'src/**'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'src/**'
  workflow_dispatch:  # Umožňuje manuální spuštění workflow

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
        pip install -r requirements.txt
        pip install -e .
        
    - name: Validate production code structure
      run: |
        # Kontrola, že v src/ nejsou importovány testovací moduly
        ! grep -r "import pytest" --include="*.py" src/
        ! grep -r "from test" --include="*.py" src/
        ! grep -r "__test__" --include="*.py" src/
        
        # Kontrola, že v src/ nejsou testovací funkce
        ! grep -r "def test_" --include="*.py" src/
        
        # Kontrola, že v src/ nejsou debug výpisy
        ! grep -r "print(\"DEBUG" --include="*.py" src/
        ! grep -r "print(\'DEBUG" --include="*.py" src/
        
        # Kontrola, že v src/ nejsou zakomentované bloky kódu (více než 3 po sobě jdoucí řádky)
        ! grep -A 3 -B 3 -P "^\\s*#.*\\n\\s*#.*\\n\\s*#.*\\n\\s*#.*" --include="*.py" src/
        
    - name: Verify imports
      run: |
        # Zkontroluje, že všechny importy fungují
        python -c "import memory_agent; print('Import successful')"
        python -c "from memory_agent import analyzer, graph, state, tools; print('Imports successful')"
